[package]
name = "adventofcode2024"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
eframe = "0.29.1"
egui = "0.29.1"
humantime = "2.1.0"
lazy_static = "1.5.0"
unicode-segmentation = "1.12.0"
